name: Build and publish package

on:
  workflow_call:
    inputs:
      package-folder:
        required: true
        type: string
    secrets:
      MAVEN_REGISTRY_TOKEN:
        required: true    

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write 
  
env:
  TAG_PREFIX: '${{ inputs.package-folder }}-'  

jobs:
  buildAndPublishPackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: adoptium:1.21
      - id: version
        name: Compute new version   
        run: ./scripts/computeNewVersion.sc --prefix='${{ env.TAG_PREFIX }}' --bump=minor >> "$GITHUB_OUTPUT"
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.new_version }}
          tag_prefix: ${{ env.TAG_PREFIX }}
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_PREFIX }}${{ steps.version.outputs.new_version }}
          release_name: ${{ inputs.package-folder }} release ${{ steps.version.outputs.new_version }}
          draft: false
          prerelease: false 
      - name: Build and publish
        run: './scripts/buildAndPublishPackage.sh ${{ inputs.package-folder }} ${{ secrets.GITHUB_TOKEN }} ${{ secrets.MAVEN_REGISTRY_TOKEN }} ${{ steps.version.outputs.new_version }}'
        shell: bash

          
